### ISSUE TITLE
use pretrained model

### ISSUE THREAD

**Issue by Github0119** [epic-kitchens/epic-kitchens-slowfast#10]
Hi there, 
I have already set up the slow-fast network and downloaded the pre-trained model. 
I want to run a demo for one of the videos, eg p01_07, but there is not working. 
Could you help me with it? thank you so much.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/98069323/161471618-5e0f560b-dd4e-4380-8a1c-6d2ba3219698.png">
Here is the code:
python tools/run_net.py --cfg configs/EPIC-KITCHENS/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 
OUTPUT_DIR /home/out EPICKITCHENS.VISUAL_DATA_DIR /home
EPICKITCHENS.ANNOTATIONS_DIR /home/temp/Epic_100_train0107.csv TRAIN.CHECKPOINT_FILE_PATH /home/temp/SlowFast.pyth

**Comment by ekazakos** [comment]
Hi,

It seems that you added in PYTHONPATH the original SlowFast repo rather than our modified version. Can you please do 
```export PYTHONPATH=/path/to/epic-kitchens-slowfast/slowfast:$PYTHONPATH``` and remove from PYTHONPATH the original SlowFast repo?

Please let me know if this solves your issue.

**Comment by Github0119** [comment]
> 

Hi,
Thank you for this. I have tried this method. But it still cannot find some files. 
I was wondering could we communicate via Whatsapp?
I am appreciate your help
<img width="851" alt="image" src="https://user-images.githubusercontent.com/98069323/161902660-93d1d6f4-3df9-423e-8a8e-5667f414a084.png">

**Comment by ekazakos** [comment]
I think we can solve your issue in here. In your screenshot above, you literally use `/path/to/` for the path of the repo. You should replace it with the actual path of the directory that contains `epic-kitchens-slowfast`. Can you try that and let me know if it resolves your issue?
