### ISSUE TITLE
Error with pretrained model.

### ISSUE THREAD

**Issue by zepol1414** [epic-kitchens/epic-kitchens-slowfast#12]
When I try to train using the pertained model of Epic Kitchens, I get the following error:

![Captura de Pantalla 2022-09-28 a las 11 40 19](https://user-images.githubusercontent.com/91973215/192746026-953a2bd1-865a-4787-b185-c745b12dd058.png)

**Comment by venom12138** [comment]
Hello! I encounter this error too. How do you fix it?
