### ISSUE TITLE
Share the test evaluation results

### ISSUE THREAD

**Issue by kishorepv** [epic-kitchens/epic-kitchens-slowfast#3]
Can you please share the verb@1, verb@5, noun@1 and noun@5 accuracy for the test set you obtained with the published checkpoint?

**Comment by dimadamen** [comment]
The checkpoint has only been trained on the "training" set. When submitting to the leaderboard for the test set, we train for both Train+Val. We are not releasing this checkpoint but you have all the information to do that training yourself.
Using the published checkpoint, you can replicate the Val results.
We are updating the ArXiv in a few days so this is reflecting all the publicly released models.
