### ISSUE TITLE
Train+Val. 

### ISSUE THREAD

**Issue by wolfworld6** [epic-kitchens/epic-kitchens-slowfast#9]
thx for your work，For the test set, I train for both Train+Val. but get this results，[INFO: logging.py:   67]: json_stats: {"noun_top1_acc": "0.00", "noun_top5_acc": "0.00", "split": "test_final", "verb_top1_acc": "0.00", "verb_top5_acc": "0.00"}，is there somwhere need to be changed in the val process？

**Comment by dimadamen** [comment]
This should not be the case. We have reported the results of Train+Val on Test in our paper.
We have used the same code base as the one in this repo. Unfortunately, we are unable to help debugging your code.
It is not clear to me what you are using as "ground truth" to report these results. The ground truth for the test set is not public and you can only get he accuracy on test by submitting your json to the test server. Is that what you have done? If so what is your submission ID number?

**Comment by wolfworld6** [comment]
> thx for your work，For the test set, I train for both Train+Val. but get this results，[INFO: logging.py: 67]: json_stats: {"noun_top1_acc": "0.00", "noun_top5_acc": "0.00", "split": "test_final", "verb_top1_acc": "0.00", "verb_top5_acc": "0.00"}，is there somwhere need to be changed in the val process？

ssssssssssssssssorry to bother you，I know！
